dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - smartcontractkit/chainlink-brownie-contracts@0.5.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'
dotenv: .env
networks:
  default: development
  development:
    verify: False
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 2500000000000000000
  ganache-local:
    verify: False
  goerli:
    verify: True
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  from_key: ${PRIVATE_KEY}